---
- name: install httpd package and list git configs
  hosts: all
  become: yes
  tasks:
   - name: Update all packages  to their 
     apt: 
      name: "*"
      state: latest
   - name: Install apache httpd
     apt:
      name: apache2
      state: present
   - name: Copy index test page
     copy:
      src: "index.html"
      dest: "/var/www/html/index.html"
      force: yes
   - name: Restart apache2
     service:
      name: apache2
      state: restarted
      
    
     
  
